### ISSUE TITLE
Bug with `@nest` and `&`

### ISSUE THREAD

**Issue by alexander-akait** [davidtheclark/postcss-resolve-nested-selector#1]
Input:
```css
.de {
    @nest
    .cd:not(:hover, :focus) & {
        & .fg {
            color: red;
        }
    }
}
```

Output:
```
.de .cd:not(:hover .fg
```
```
:focus) .de .fg
```

Expected:
```
.de
```
```
.cd:not(:hover):not(:focus) .de
```
```
.cd:not(:hover):not(:focus) .de .fg
```

Original issue: https://github.com/stylelint/stylelint/issues/2453
